### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by pleszkiewicz** [magic-script/magic-script-components-react-native#384]
### Description

Enable applications to launch at any page route.

### Completion status

- [x] Android
- [x] iOS

**Comment by SPaluchiewiczSofomo** [comment]
There is no need to add implementation in `magic-script-components-react-native` repository/package. Whole implementation is done in final app: example provided to Catalog with this PR: https://github.com/magic-script/magic-script-components-catalog/pull/115

I attach below initial steps for iOS to set Deep Linking - should be updated with steps for Android and for Common (JSX).

Add required import

```objectivec
#import <React/RCTLinkingManager.h>
```

- Update AppDelegate part of

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

from

```objectivec
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Catalog"
                                            initialProperties:nil];
```

to

```objectivec
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

  NSMutableDictionary *initialProperties = [NSMutableDictionary new];
  if ([launchOptions objectForKey:UIApplicationLaunchOptionsURLKey] != nil) {
    NSURL *initialUrl = [launchOptions objectForKey:UIApplicationLaunchOptionsURLKey];
    initialProperties[@"initialUrl"] = [initialUrl absoluteString];
  }

  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Catalog"
                                            initialProperties:initialProperties];
```

- Set `URL Types` in app XCode: TARGETS -> APP TARGET -> Info -> URL Types based on below example:

![alt text][urltypesexample]
[urltypesexample]: ./urlTypesExample.png "URL Types Example"

![urlTypesExample](https://user-images.githubusercontent.com/42351184/74938246-ec000400-53ed-11ea-9584-ff7133b08424.png)

or edit `Info.plist` with below lines (note: remember to update AppURLSchema_Name & AppURLSchema)

AppURLSchema is the URL schema which trigger app lunch

```xml
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>AppURLSchema_Name</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>AppURLSchema</string>
			</array>
		</dict>
	</array>
```

**Comment by SPaluchiewiczSofomo** [comment]
Updated iOS documentation:

[deepLinking_iOS.pdf](https://github.com/magic-script/magic-script-components-react-native/files/4234996/deepLinking_iOS.pdf)

**Comment by SPaluchiewiczSofomo** [comment]
Android documentation:
[deeplinking_android.pdf](https://github.com/magic-script/magic-script-components-react-native/files/4235743/deeplinking_android.pdf)

Common documentation:
[deeplink_react-native.pdf](https://github.com/magic-script/magic-script-components-react-native/files/4235744/deeplink_react-native.pdf)
