### ISSUE TITLE
Pass initial uri parameter in Scene.onAppStart event.

### ISSUE THREAD

**Issue by pleszkiewicz** [magic-script/magic-script-components-react-native#538]
### [<< Main](https://github.com/magic-script/magic-script-components/issues/294)

For Android and iOS, we need to expose **onAppStart** event in the **Scene** component and pass `uri` param in there. 

On Lumin, there are more properties passed in the **onAppStart** event but they are not related/not intuitive and we can ignore them for now.
```
{ 
      uri,
      isInternetConnected,
      isWiFiConnected,
      isWiFiEnabled,
      isShareableApp
}
```

### Completion status
- [x] Android
- [x] iOS

**Comment by grozdanov** [comment]
MXSCOMP-242
