### ISSUE TITLE
Prism Interaction - bug fixing, intra platform alignment.

### ISSUE THREAD

**Issue by SPaluchiewiczSofomo** [magic-script/magic-script-components-react-native#544]
- [x] [**iOS**] wrong position for PrismContextMenu when user change Prism scale
- [x] [**iOS**] allow only gestures for Prism Interaction when Prism in editMode
- [x] [**iOS**] update prism corner model (for edit mode)
- [x] [**iOS**] hitTest does not work for context menu when clicked from behind the prism
- [x] [**Android**] edit mode model instead of red cube and better button graphics quality,
- [x]  [**Android**] limit min prism distance to prismRadius

**Comment by grozdanov** [comment]
MXSCOMP-263
